### ISSUE TITLE
glMultiDrawElementsBaseVertex: missing group attribute

### ISSUE THREAD

**Issue by luca-piccioni** [KhronosGroup/OpenGL-API#2]
The `glMultiDrawElementsBaseVertex*` commands definitions miss the group attribute for the argument `mode`. Other _Draw_ commands have the mode argument typed with the _PrimitiveType_ group; I don't see any reason why the `glMultiDrawElementsBaseVertex*` should be excluded. Indeed I suggest to update with:

```
<command>
  <proto>void <name>glMultiDrawElementsBaseVertex</name></proto>
  <param group="PrimitiveType"><ptype>GLenum</ptype> <name>mode</name></param>
  ...
</command>
```

**Comment by oddhack** [comment]
The groups and group attribute tags are holdovers from the ancient SGI ".spec" format, and have rarely been kept up to date, because Khronos doesn't use them for anything. Making improvements is fine, so long as they have no semantic effects on the generated headers, but I'll be more likely to accept such changes if you propose them in the form of pull requests rather than issues.
