### ISSUE TITLE
OpenGL 4.6: Constant c not defined anymore in 8.15 for minification/magnification.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-API#34]
Section 8.14 says:

> If λ(x,y) is less than or equal to the constant c (see section 8.15) the texture is said to be magnified; if it is greater, the texture is minified.

But 8.15 doesn't define this "constant c". And I don't believe there is a definition of it anywhere.

Note that older versions of the OpenGL specification actually defined "constant c" in 8.15. The paragraph seems to have disappeared between 4.4 and 4.5. Perhaps the idea was to remove the "constant c" bit and replace it with 0, but that apparently didn't fully manifest.

**Comment by pdaniell-nv** [comment]
This was discussed internally in https://www.khronos.org/members/login/bugzilla/show_bug.cgi?id=9997. It was decided that the switch-over point should always be 0 (c=0) since that's what everyone does. It appears Section 8.14 wasn't updated accordingly.

I think Section 8.14 should be updated to say:
> If λ(x,y) is less than or equal to zero the texture is said to be magnified; if it is greater, the texture is minified.

The OpenGL ES 3.2 spec already has this fix.

**Comment by pdaniell-nv** [comment]
Assigned to @oddhack to modify the OpenGL 4.6 spec in the same way that was done for OpenGL ES 3.2 to remove the reference to "constant c" and use the proposed change in the comment above.

**Comment by oddhack** [comment]
The fixes identified by @pdaniell-nv will be in the next GL & ES spec updates, coming soon.
